# Generated by Django 4.2.24 on 2025-09-25 00:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('atc_code', models.CharField(db_index=True, max_length=32)),
                ('label', models.CharField(max_length=255)),
                ('form', models.CharField(blank=True, max_length=64, null=True)),
                ('strength', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'unique_together': {('atc_code', 'label')},
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_key', models.CharField(db_index=True, editable=False, max_length=64)),
                ('sku', models.CharField(db_index=True, max_length=64)),
                ('min_threshold', models.IntegerField(default=0)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pharmacy.drug')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospital.facility')),
            ],
            options={
                'unique_together': {('facility', 'sku')},
            },
        ),
        migrations.CreateModel(
            name='InventoryLot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_key', models.CharField(db_index=True, editable=False, max_length=64)),
                ('lot_code', models.CharField(max_length=64)),
                ('expiration', models.DateField(blank=True, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='pharmacy.inventoryitem')),
            ],
            options={
                'unique_together': {('item', 'lot_code')},
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_key', models.CharField(db_index=True, editable=False, max_length=64)),
                ('movement_type', models.CharField(max_length=16)),
                ('qty', models.IntegerField()),
                ('at', models.DateTimeField(db_index=True)),
                ('reason', models.CharField(blank=True, max_length=128, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pharmacy.inventoryitem')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.inventorylot')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant_key', 'at', 'movement_type'], name='pharmacy_in_tenant__6acd3c_idx')],
            },
        ),
    ]
