# Generated by Django 4.2.24 on 2025-10-01 14:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='code',
            field=models.CharField(db_index=True, default=uuid.uuid4, max_length=46, unique=True),
        ),
    ]
