# Generated by Django 4.2.24 on 2025-10-05 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_alter_region_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='pole',
            new_name='poles',
        ),
    ]
